name: Auto Retrain Model

on:
  schedule:
    # Check for dataset updates every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Manual trigger option
  
env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  DATASET_NAME: "vinoku89/svg-code-generation"

jobs:
  check-and-retrain:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Verify GPU availability
      run: |
        nvidia-smi
        echo "CUDA Version: $(nvcc --version || echo 'CUDA not found')"
        
    - name: Install uv (if not already installed)
      run: |
        if ! command -v uv &> /dev/null; then
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source $HOME/.cargo/env
        fi
        uv --version
        
    - name: Install dependencies with uv
      run: |
        uv sync
        
    - name: Check dataset updates
      id: check_updates
      run: |
        uv run python ./src/check_dataset_update.py
        
    - name: Train model
      if: steps.check_updates.outputs.should_retrain == 'true'
      run: |
        uv run python ./src/train_llm.py
        
    - name: Upload to Hugging Face
      if: steps.check_updates.outputs.should_retrain == 'true'
      run: |
        uv run python ./src/upload_model_to_hf.py
        
    - name: Cleanup GPU memory
      if: always()
      run: |
        python -c "
        try:
            import torch
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
                print('GPU cache cleared')
        except ImportError:
            pass
        "